App:
  annotations:
    velocity.tech.v1/id: "ml-labeling-app"
    velocity.tech.v1/dependsOn: bucket

  containers:
    image: jdvincent/ml-image-to-tensor-s3-app:latest
  
  envVars:
    S3_NAME: "{velocity.v1:bucket.exports.path}"

  ingress:
    ingressClassName: null
    host: "api-{velocity.v1.domainSuffix}"

cronJob:
  annotations:
    velocity.tech.v1/id: "argo-ml-pipeline"
    velocity.tech.v1/dependsOn: bucket

  containers:
    image: jdvincent/ml-image-to-tensor-s3-job:latest
  
  envVars:
    ARGO_SERVER_HOST: my-argo-workflows-server.argo
    ARGO_SERVER_PORT: "2746"
    ARGO_TOKEN: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkEyY3FxQ19uWmRxNHhtVW5xN1RZSlktdE1MZXROdGlqMmRMQXJLUThRM2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwcC5zZXJ2aWNlLWFjY291bnQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYjM1NmQxYjEtYmQ1Ni00MzJjLTgxY2EtMDcwZjdmMDI1OGIxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ286YXBwIn0.baVIdXzagNvI0yLgpbNPn6Pc0GqjmNIgm0VSM7msE50bFCU9421LTeyf3QxZ8WL6vQPAi0uo6fmzQ03lkI-vz9iV8FZQuA-wEg1SptdizEDQKdvHNd00CWTwKj0IEN51oDVvB5gWuU5-tPHdS28U3rvVmzMNs4Ucf-1_X2w-jRJvRPl_ECLb6PusUsj0p5Jg5Nt_Pyeu19q8bXEZ-2ZOg2KVJiyFnRyKpdzfcb9Ckl3r-1KSjdskqRQgcmKpMrILE5VBSKObLzXbw4ZGS25yQdcKVOa0r36890wVOZK2BhVjPdbnN3-hMcqsRl3_ITHS7EyjsSivS-fy-ndU-RVvUg
    S3_NAME: "{velocity.v1:bucket.exports.path}"

S3:
  annotations:
    velocity.tech.v1/exports-path: path="spec.name"
    velocity.tech.v1/id: bucket
  name: "{velocity.v1.generate:cloudResourcePrefix}-my-bucket"
