---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: {{ .Values.App.annotations.velocityID }}
    velocity.tech.v1/dependsOn: {{ .Values.App.annotations.velocityDependsOn }}
  name: ml-labeling-app
  labels:
    app: ml-labeling-app
spec:
  selector:
    matchLabels:
      app: ml-labeling-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-labeling-app
    spec:
      containers:
        - name: ml-labeling-app
          image: {{ .Values.App.containers.image }}
          envFrom:
            - secretRef:
                name: aws-cred-developer
          env:
            - name: S3_NAME
              value: {{ .Values.App.envVars.S3_NAME }}
          ports:
            - name: ml-labeling-app
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ml-labeling-app
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: ml-labeling-app
  selector:
    app: ml-labeling-app
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-labeling-app
spec:
  ingressClassName: null
  rules:
    - host: {{ .Values.App.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-labeling-app
                port:
                  number: 8000
