apiVersion: batch/v1
kind: CronJob
metadata:
  name: argo-ml-pipeline
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: argo-ml-pipeline
              image: jdvincent/ml-image-to-tensor-s3-job:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: ARGO_SERVER_HOST
                  value: my-argo-workflows-server.default
                - name: ARGO_SERVER_PORT
                  value: "2746"
                - name: ARGO_TOKEN
                  value: 
                - name: AWS_ACCESS_KEY_ID
                  value: 
                - name: AWS_SECRET_ACCESS_KEY
                  value: 
                - name: S3_RAW_IMAGES
                  value: velocity-demo-raw-images
                - name: S3_PROCESSED_IMAGES
                  value: velocity-demo-processed-images
          restartPolicy: OnFailure
