apiVersion: batch/v1
kind: CronJob
metadata:
  name: argo-ml-pipeline
  {{- with .Values.cronJob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            velocity.v1.tech/id: argo-ml-job
            velocity.v1.tech/dependsOn: bucket
        spec:
          containers:
            - name: argo-ml-pipeline
              image: {{ .Values.cronJob.containers.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: aws-cred-developer
              env:
                - name: ARGO_SERVER_HOST
                  value: {{ .Values.cronJob.envVars.ARGO_SERVER_HOST | quote }}
                - name: ARGO_SERVER_PORT
                  value: {{ .Values.cronJob.envVars.ARGO_SERVER_PORT | quote }}
                - name: ARGO_TOKEN
                  value: {{ .Values.cronJob.envVars.ARGO_TOKEN | quote }}
                - name: S3_NAME
                  value: {{ .Values.cronJob.envVars.S3_NAME | quote }}
          restartPolicy: OnFailure
