apiVersion: batch/v1
kind: CronJob
metadata:
  name: argo-ml-pipeline
  annotations:
    velocity.v1.tech/id: {{ .Values.cronJob.annotations.velocityID }}
    velocity.tech.v1/dependsOn: {{ .Values.cronJob.annotations.velocityDependsOn }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            velocity.v1.tech/id: argo-ml-job
            velocity.v1.tech/dependsOn: bucket
        spec:
          containers:
            - name: argo-ml-pipeline
              image: {{ .Values.cronJob.containers.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: aws-cred-developer
              env:
                - name: ARGO_SERVER_HOST
                  value: {{ .Values.cronJob.envVars.ARGO_SERVER_HOST }}
                - name: ARGO_SERVER_PORT
                  value: {{ .Values.cronJob.envVars.ARGO_SERVER_PORT }}
                - name: ARGO_TOKEN
                  value: {{ .Values.cronJob.envVars.ARGO_TOKEN }}
                - name: S3_NAME
                  value: "{velocity.v1:bucket.exports.path}"
          restartPolicy: OnFailure
