---
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  annotations:
    velocity.tech.v1/exports-path: path="spec.name"
    velocity.tech.v1/id: bucket
  name: "{velocity.v1.generate:cloudResourcePrefix}-my-bucket-var-service-id"
spec:
  name: "{velocity.v1.generate:cloudResourcePrefix}-my-bucket"
