---
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  {{- with .Values.App.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.S3.name | quote }}
spec:
  name: {{ .Values.S3.name | quote }}
